name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.0

        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}

          script: |
            set -e

            cd /home/rakibul/qbag/backend

            echo "Pull latest code..."
            git pull origin main

            echo "Build & Restart..."
            docker compose up -d --build

            echo "Run migrations..."
            docker exec qbag-backend alembic upgrade head

            echo "Clean unused images..."
            docker image prune -f

            echo "Backend Deployment completed."

            cd ~/qbag/frontend

            git pull origin main

            pnpm install --frozen-lockfile

            pnpm build

            sudo rm -rf /var/www/qbag/*

            sudo cp -r dist/* /var/www/qbag/

            sudo systemctl reload nginx